version: '3'
services:
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=RybaPila1!PiesJadl
      - MSSQL_PID=Express
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"

  backend:
    image: ja3ekja/maven:version2.0
    command: mvn spring-boot:run
    volumes:
      - "./:/usr/src/mymaven"
      - "~/.m2:/root/.m2"
    ports:
      - "8080:8080"
    depends_on:
      - db

  tests:
    image: ja3ekja/maven:version2.0
    command: mvn test
    volumes:
      - "./:/usr/src/mymaven"
      - "~/.m2:/root/.m2"
    ports:
      - "8080:8080"
    depends_on:
      - db